version: "3"
services:
  app:
    container_name: app
    build: .
    depends_on:
       - mysql
    ports:
      - 8001:80
    volumes:
      - "./:/usr/share/nginx"
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"

  mysql:
    image: mysql:5.7
    container_name: db
    expose:
      - "3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: passwd